name: Generate Snake

on:
  schedule: # Execute o script uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Gus-hcs
          outputs: dist/snake.svg

      - name: Push Snake Animation to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: dist
